# The Docker image that will be used to build your app
image: gradle:8-jdk17-alpine
create-pages:
  pages:
    # The folder that contains the files to be exposed at the Page URL
    publish: public
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  script:
    - gradle -Dorg.gradle.welcome=never --no-daemon compileJava
